name: Validate with hassfest

on:
  push:
    - ["master"]
  pull_request:
    - ["master"]
  release:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: home-assistant/actions/hassfest@master